packages:
  - apps/*
  - apps/desktop/e2e
  - packages/*
  - tools/*

allowBuilds:
  edgedriver: false
  esbuild: true
  geckodriver: false

catalog:
  "@codemirror/autocomplete": ^6.20.0
  "@codemirror/commands": ^6.10.3
  "@codemirror/lang-markdown": ^6.5.0
  "@codemirror/language": ^6.12.2
  "@codemirror/language-data": ^6.5.2
  "@codemirror/lint": ^6.9.2
  "@codemirror/search": ^6.7.0
  "@codemirror/state": ^6.6.0
  "@codemirror/view": ^6.40.0
  "@hugeicons/core-free-icons": ^4.1.1
  "@hugeicons/react": ^1.1.6
  "@lezer/common": ^1.4.0
  "@lezer/highlight": ^1.2.3
  "@lezer/markdown": ^1.6.1
  "@lezer/yaml": ^1.0.4
  "@tailwindcss/vite": ^4.2.2
  "@tanstack/devtools-vite": ^0.7.0
  "@tauri-apps/plugin-clipboard-manager": ^2.3.2
  "@tauri-apps/plugin-dialog": ^2.6.0
  "@tauri-apps/plugin-store": ^2.4.2
  "@types/katex": ^0.16.7
  "@types/node": ^24
  "@welldone-software/why-did-you-render": ^10.0.1
  beautiful-mermaid: ^1.1.3
  cmdk: ^1.1.1
  dompurify: ^3.4.7
  katex: ^0.16.25
  motion: ^12.43.0
  node-emoji: ^2.2.0
  react-resizable-panels: ^4.7.4
  tailwindcss: ^4.2.2
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.22
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  yaml: ^2.8.3
  zustand: ^5.0.12

catalogMode: prefer
overrides:
  "@voidzero-dev/vite-plus-test>vite": 8.0.14
  basic-ftp: 5.3.1
  fast-xml-builder: 1.1.7
  fast-xml-parser: 5.7.0
  ip-address: 10.1.1
  lodash: 4.18.1
  picomatch: 4.0.4
  postcss: 8.5.15
  serialize-javascript: 7.0.5
  vite: "catalog:"
  vitest: "catalog:"
  "website>vite": "npm:vite@^8.0.16"
  ws: 8.20.1
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
